# The Wine Challenge

Original code below.

In [3]:
# wineheader.py

from sklearn import preprocessing
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
import numpy as np                 
import pandas as pd 
import sklearn
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter

In [4]:
# Taken from wine-data.py

# Read-in the data
data = pd.read_csv('winequality-red.csv', sep=';')

# Getting to know the data
print ('\n EXTRACT FROM DATA SET \n')
print(data.head(3))

# Count of each target variable
print('\n \n COUNTS PER QUALITY: \n')
print(Counter(data['quality']))
print('\n')


 EXTRACT FROM DATA SET 

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  

 
 COUNTS PER QUALITY: 

Counter({5: 681, 6: 638, 7: 199, 4: 53, 8: 18, 3: 10})




In [5]:
# Taken from prepare-data.py

# Replace quality by Reviews
reviews = []
for i in data['quality']:
    if i >= 1 and i <= 3:
        reviews.append('1')
    elif i >= 4 and i <= 7:
        reviews.append('2')
    elif i >= 8 and i <= 10:
        reviews.append('3')
data['Reviews'] = reviews

print('\n NUMBER OF WINES PER QUALITY-REVIEW \n')
print(Counter(data['Reviews']))



 NUMBER OF WINES PER QUALITY-REVIEW 

Counter({'2': 1571, '3': 18, '1': 10})


In [6]:
# Taken from wine-model.py

#del data['quality']

# Split data into test and training data

y = data.Reviews
X = data.drop('Reviews', axis=1)
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=test_size,
                                                    random_state=123,
                                                    stratify=y)

# Build and train machine learning model
#model = INSERT-MODEL-HERE
#model.fit(X_train, y_train)
#model_predict = model.predict(X_test)

# Calculae and print the accuracy of the model for the test data
#model_acc_score = accuracy_score(y_test, model_predict)
#print('Your model scored the following accuracy:')
#print(model_acc_score*100)


In [7]:
# Taken from wine-model-2.py

# Build and train machine learning model
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr_predict = lr.predict(X_test)
lr_predict_train = lr.predict(X_train)

# Print accuracy score for test data
lr_acc_score = accuracy_score(y_test, lr_predict)
print('The accuracy of the model for the test data is:')
print(lr_acc_score*100)

# Print accuracy score for training data
lr_acc_score = accuracy_score(y_train, lr_predict_train)
print('The accuracy of the model for the training data is:')
print(lr_acc_score*100)

# Print confusion matrix for test data
lr_conf_matrix = confusion_matrix(y_test, lr_predict)
lr_conf_matrix=lr_conf_matrix.transpose()
print('Confusion matrix for test data')
print(lr_conf_matrix)

# Print confusion matrix for training data
lr_conf_matrix = confusion_matrix(y_train, lr_predict_train)
lr_conf_matrix=lr_conf_matrix.transpose()
print('Confusion matrix for training data')
print(lr_conf_matrix)



The accuracy of the model for the test data is:
98.75
The accuracy of the model for the training data is:
99.13995308835027
Confusion matrix for test data
[[  1   0   0]
 [  1 314   3]
 [  0   0   1]]
Confusion matrix for training data
[[   5    0    0]
 [   3 1257    8]
 [   0    0    6]]


/Users/horatiu/anaconda3/envs/tf/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
